### ISSUE TITLE
How to install or use?

### ISSUE THREAD

**Issue by MazenS** [AlmostInteractive/ESP32-S3-Box-3-Voice-Assistant-Sensor-Dock#22]
Hello there,

This looks really cool and excuse my ignorance but how do I install it on my S3 box?
Do I firstly install BigBobba's custom firmware, then apply your yaml?
Is there something else I need to do first?

Another fun question - Can the IR blaster be controlled by Home Assistant?

Thanks a lot

**Comment by AlmostInteractive** [comment]
It's just like any ESPHome yaml file, so you can install it through the ESPHome Dashboard in HomeAssistant or via the command line.  And yes, the IR blaster can be triggered from HA to send any of the recorded IR codes.

**Comment by MazenS** [comment]
Awesome - and thank you for the prompt reply.
I'll give it a try tomorrow morning and report back - once I've done a little more reading.

**Comment by MazenS** [comment]
```
Failed config

micro_wake_word: [source /config/esphome/esp32-s3box-3.yaml:227]
  models: 
    - okay_nabu
  on_wake_word_detected: 
    - if: 
        condition: 
          lambda: return id(mem_va_speaker_mode).state != "Mute";
        then: 
          - 
            Expected a file scheme or a URL scheme with host.
            media_player.play_media: ''
          - wait_until: 
              condition: 
                not: media_player.is_idle
              timeout: 2sec
```

So trying to update the yaml via ESP Home Builder gave me the following error.
I may as well run through my installation steps in-case I've done something wrong earlier.

-  The box had the Home Assistant Assist firmware running to start with.
- I replaced this with the BigBobba's.
- In home assistant I went to ESP Home Builder, found and connected to the device.
- Copy and pasted your yaml and pressed install.

**Comment by neilchen1985** [comment]
Same here, looking for solution

**Comment by igorsantos07** [comment]
I'm trying to install it as well, but I got lost at the start, when replacing some fields from the original YAML code...

My original HA configuration was the following:
```yaml
substitutions:
  name: esp32-s3-box-3-2e0790
  friendly_name: ESP32 S3 Box 3 2e0790
packages:
  esphome.voice-assistant: github://esphome/wake-word-voice-assistants/esp32-s3-box-3/esp32-s3-box-3.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: ««a long string»»
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```

However, the new YAML requests only `encryption_key`, which I guess should be `api.encryption.key` from the original config, and `ota_password` which I have no clue what would be 😅 

My questions are:
1. where do I get the `ota_password` from?
2. do we need to install the BigBobba's firmware first? All I did once the S3 arrived was follow the [standard tutorial from the HA blog](https://www.home-assistant.io/voice_control/s3_box_voice_assistant/).
3. I see the original firmware had a reference to a YAML from the ESPHome repository. Couldn't we do the same, so it's updatable, and then we don't have to copy a ton of YAML? 🙏
